---
# tasks file for roles/apache
- name: install apache and firewalld packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
    - httpd
    - firewalld
- name: start and enable httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
- name: start and enable httpd service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
- name: allow http from firewall
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
- name: deploy a template 
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

