---
- name: configure repositories in all managed nodes
  hosts: all
  tasks:
    - name: Create BaseOS Repository 
      ansible.builtin.yum_repository:
        name: "baseos" 
        description: "Baseos Description" 
        baseurl: http://content/rhel9.0/x86_64/dvd/BaseOS 
        gpgcheck: yes 
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release 
        enabled: yes
    - name: Create Appstream Repository
      ansible.builtin.yum_repository: 
        name: "appstream" 
        description: "App Description" 
        baseurl: http://content/rhel9.0/x86_64/dvd/AppStream 
        gpgcheck: yes 
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release 
        enabled: yes
