---
- name: Collect the all node information
  hosts: all
  tasks:
    - name: copy the template to the managed node
      ansible.builtin.template:
        src: myhosts.j2
        dest: /etc/myhosts 
      when: inventory_hostname in groups['dev']

