---
- name: install packages in group of hosts
  hosts: dev,test,prod
  tasks:
    - name: installing php and mariadb-server
      ansible.builtin.dnf:
        name:
          - php
          - mariadb
        state: present 
- name: install development tools package and update all packages in dev group
  hosts: dev
  tasks:
    - name: installing group package 
      ansible.builtin.dnf:
        name: '@RPM Development Tools' 
        state: present
    - name: update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
